name: NodeJS with Webpack

defaults:
  run:
    shell: bash
    working-directory: ui

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Download dependencies
      run: npm ci
    
    - name: Build
      run: npm run build --if-present
    
    - name: Running Test
      run: npm test

  # CVE scanning 
  cvescan:
    name: CVE Scanning
    runs-on: ubuntu-latest
    needs: [ build ]
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npx --yes auditjs ossi --whitelist allow-list.json
